swagger: "2.0"
info:
  title: A API Server Sample
  version: 0.1.0
consumes:
- application/json
produces:
- application/jaon
schemes:
- http
paths:
  /address:
    get:
      parameters:
        - name: zipcode
          in: query
          type: number
          default: 1638001
      responses:
        200:
          description: Successful
          schema:
            type: object
            properties:
              message:
                type: string
              results:
                type: array
                items:
                  type: object
                  properties:
                    address1:
                      type: string
                    address2:
                      type: string
                    address3:
                      type: string
                    kana1:
                      type: string
                    kana2:
                      type: string
                    kana3:
                      type: string
                    prefcode:
                      type: string
                    zipcode:
                      type: string
              status:
                type: integer




