// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/jaon"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "A API Server Sample",
    "version": "0.1.0"
  },
  "paths": {
    "/address": {
      "get": {
        "parameters": [
          {
            "type": "number",
            "default": 1638001,
            "name": "zipcode",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                },
                "results": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "address1": {
                        "type": "string"
                      },
                      "address2": {
                        "type": "string"
                      },
                      "address3": {
                        "type": "string"
                      },
                      "kana1": {
                        "type": "string"
                      },
                      "kana2": {
                        "type": "string"
                      },
                      "kana3": {
                        "type": "string"
                      },
                      "prefcode": {
                        "type": "string"
                      },
                      "zipcode": {
                        "type": "string"
                      }
                    }
                  }
                },
                "status": {
                  "type": "integer"
                }
              }
            }
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/jaon"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "A API Server Sample",
    "version": "0.1.0"
  },
  "paths": {
    "/address": {
      "get": {
        "parameters": [
          {
            "type": "number",
            "default": 1638001,
            "name": "zipcode",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                },
                "results": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "address1": {
                        "type": "string"
                      },
                      "address2": {
                        "type": "string"
                      },
                      "address3": {
                        "type": "string"
                      },
                      "kana1": {
                        "type": "string"
                      },
                      "kana2": {
                        "type": "string"
                      },
                      "kana3": {
                        "type": "string"
                      },
                      "prefcode": {
                        "type": "string"
                      },
                      "zipcode": {
                        "type": "string"
                      }
                    }
                  }
                },
                "status": {
                  "type": "integer"
                }
              }
            }
          }
        }
      }
    }
  }
}`))
}
