// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi A API Server Sample

    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 0.1.0

    Consumes:
    - application/json

    Produces:
    - application/jaon

swagger:meta
*/
package restapi
